package codex

import (
	"fmt"
	"os"
	"path/filepath"

	"github.com/Herrscherd/herrscher-contracts"
)

// gatewayConfigTOML renders the config.toml that declares the Neublox gateway
// as a model provider.
//
// wire_api = "responses" — NOT "chat" as an earlier draft of this task
// assumed. codex 0.146.0 hard-rejects "chat": `codex exec` refuses to start
// and reports "wire_api = \"chat\" is no longer supported. ... set
// wire_api = \"responses\" in your provider config." (verified live against
// the installed CLI, see https://github.com/openai/codex/discussions/7782).
// The gateway must therefore speak the Responses wire format, not Chat
// Completions. The token is NOT written to the file — it is referenced by
// env_key and supplied at run time, so a CODEX_HOME left behind on disk never
// contains a secret.
func gatewayConfigTOML(baseURL string) string {
	return fmt.Sprintf(`# Generated by herrscher. Do not edit: rewritten on every session.
model_provider = "neublox"

[model_providers.neublox]
name = "Neublox"
base_url = %q
env_key = %q
wire_api = "responses"
`, baseURL, contracts.EnvNeubloxToken)
}

// writeGatewayHome materializes a disposable, per-spawn CODEX_HOME under dir
// and returns its path. os.MkdirTemp is used rather than a fixed name so that
// two concurrent gateway sessions never share a directory (and therefore
// never race on one config.toml or bleed one session's base_url/token pairing
// into another's spawn), and so the 0o700 mode is actually enforced by
// creation rather than being a no-op MkdirAll over a directory — or symlink —
// that may already exist at a guessable path. The caller is responsible for
// removing the returned directory once the session that owns it ends; see
// oneShotResponder and streamResponder Close in stream.go. The file is 0600:
// it holds no secret, but it does describe where the user's traffic is routed.
func writeGatewayHome(dir, baseURL string) (string, error) {
	home, err := os.MkdirTemp(dir, "codex-home-*")
	if err != nil {
		return "", fmt.Errorf("codex gateway home: %w", err)
	}
	path := filepath.Join(home, "config.toml")
	if err := os.WriteFile(path, []byte(gatewayConfigTOML(baseURL)), 0o600); err != nil {
		return "", fmt.Errorf("codex gateway config: %w", err)
	}
	return home, nil
}
