package codex

import (
	"fmt"
	"os"
	"path/filepath"
)

// gatewayConfigTOML renders the config.toml that declares the Neublox gateway
// as a model provider.
//
// wire_api = "responses" — NOT "chat" as an earlier draft of this task
// assumed. codex 0.146.0 hard-rejects "chat": `codex exec` refuses to start
// and reports "wire_api = \"chat\" is no longer supported. ... set
// wire_api = \"responses\" in your provider config." (verified live against
// the installed CLI, see https://github.com/openai/codex/discussions/7782).
// The gateway must therefore speak the Responses wire format, not Chat
// Completions. The token is NOT written to the file — it is referenced by
// env_key and supplied at run time, so a CODEX_HOME left behind on disk never
// contains a secret.
func gatewayConfigTOML(baseURL string) string {
	return fmt.Sprintf(`# Generated by herrscher. Do not edit: rewritten on every session.
model_provider = "neublox"

[model_providers.neublox]
name = "Neublox"
base_url = %q
env_key = "NEUBLOX_TOKEN"
wire_api = "responses"
`, baseURL)
}

// writeGatewayHome materializes a disposable CODEX_HOME under dir and returns
// its path. The file is 0600: it holds no secret, but it does describe where
// the user's traffic is routed.
func writeGatewayHome(dir, baseURL string) (string, error) {
	home := filepath.Join(dir, "codex-home")
	if err := os.MkdirAll(home, 0o700); err != nil {
		return "", fmt.Errorf("codex gateway home: %w", err)
	}
	path := filepath.Join(home, "config.toml")
	if err := os.WriteFile(path, []byte(gatewayConfigTOML(baseURL)), 0o600); err != nil {
		return "", fmt.Errorf("codex gateway config: %w", err)
	}
	return home, nil
}
